server:
  port: 9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: app-cep
  #redis:
   # host: localhost
    #port: 6379
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000