server:
  port: 9090
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    app-person:
      path: /api/v1/**
      url: http://app-person:9091/api/v1/
    oauth:
      path: /oauth/**
      url: http://auth-server:8090/oauth/

security:
  oauth2:
    resource:
      userInfoUri: http://auth-server:8090/validateUser
      #userInfoUri: http://localhost:8090/oauth/token

